# Generated by Django 5.1 on 2024-09-27 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participacaoescala',
            options={'verbose_name_plural': 'Participacoes'},
        ),
        migrations.AddField(
            model_name='participacaoescala',
            name='confirmacao',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
