# Generated by Django 5.1 on 2025-03-20 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizacao',
            options={'verbose_name_plural': 'Organizacoes'},
        ),
        migrations.CreateModel(
            name='Convite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_destinatario', models.EmailField(max_length=100)),
                ('nome_remetente', models.CharField(max_length=100)),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convites', to='escala.equipe')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_equipe', models.CharField(max_length=6)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soliticacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Solicitacoes',
            },
        ),
    ]
