# Generated by Django 5.1 on 2025-03-20 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0002_alter_organizacao_options_convite_solicitacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to=settings.AUTH_USER_MODEL),
        ),
    ]
