# Generated by Django 5.2.15 on 2026-08-03 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0006_create_users_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleConfirmationReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_hours', models.PositiveSmallIntegerField(choices=[(72, '72 hours'), (48, '48 hours'), (24, '24 hours')])),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('participation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmation_reminders', to='escala.scheduleparticipation')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('participation', 'window_hours'), name='unique_confirmation_reminder_window')],
            },
        ),
    ]
