# Generated by Django 5.2.15 on 2026-08-03 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0007_scheduleconfirmationreminder'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyUnavailabilityReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_unavailability_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'month'), name='unique_monthly_unavailability_reminder')],
            },
        ),
    ]
