# Generated by Django 5.2.15 on 2026-08-06 02:17

import django.db.models.deletion
import escala.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0008_monthlyunavailabilityreminder'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=escala.models.generate_invitation_link_token, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invitation_links', to=settings.AUTH_USER_MODEL)),
                ('organization', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitation_link', to='escala.organization')),
                ('team', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitation_link', to='escala.team')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('organization__isnull', False), ('team__isnull', True)), models.Q(('organization__isnull', True), ('team__isnull', False)), _connector='OR'), name='invitation_link_has_one_target')],
            },
        ),
    ]
