# Generated by Django 5.2.15 on 2026-08-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0010_schedule_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='visibility',
            field=models.CharField(
                choices=[
                    ('discoverable', 'Descoberta'),
                    ('private', 'Privada'),
                    ('closed', 'Fechada'),
                ],
                default='discoverable',
                max_length=12,
            ),
        ),
    ]
